version: '3.9'

services:
  db:
    image: postgres:15
    container_name: legis_ai_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: legis_ai
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:
